app/models.py
from . import db,models
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))  
        


class User(UserMixin,db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index = True)
    email = db.Column(db.String(255),unique = True,index = True)
    role_id = db.Column(db.Integer,db.ForeignKey('roles.id'))
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    password_hash = db.Column(db.String(255))
    pitches = db.relationship('Pitch', backref='user', lazy=True)


    @property
    def password(self):
        raise AttributeError('You cannnot read the password attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.password_hash,password)

    def __repr__(self):
        return f'User {self.username}'


class Role(db.Model):
    __tablename__ = 'roles'

    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(255))
    users = db.relationship('User',backref = 'role',lazy = "dynamic")


    def __repr__(self):
        return f'User {self.name}' 



class Pitch(db.Model):

  '''
  Class to define pitch objects
  '''
  __tablename__ = 'pitches'

  id = db.Column(db.Integer,primary_key=True)
  pitch = db.Column(db.String(255))
  category = db.Column(db.String(255))
  title = db.Column(db.String(255))
  vote_count = db.Column(db.Integer)
  added_date = db.Column(db.DateTime,default=datetime.utcnow)
  author = db.Column(db.Integer,db.ForeignKey('users.id'))
#   likes and dislike 
  

  def __repr__(self):
    return f'Pitch{self.pitch}'

class Comment(db.Model):
    
  '''
  Comments data
  '''
  __tablename__ = 'comments'
  id = db.Column(db.Integer,primary_key=True)
  comment = db.Column(db.String(255))
  title = db.Column(db.Integer,db.ForeignKey('pitches.id'))
  poster = db.Column(db.Integer,db.ForeignKey('users.id'))
  
  def save_comment(self):
    db.session.add(self)
    db.session.commit()

  def __repr__(self):
    return f'{self.comment}'       


 

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,SelectField
from wtforms.validators import Required

class ReviewForm(FlaskForm):

    title = StringField('Review title',validators=[Required()])
    review = TextAreaField('Movie review')
    submit = SubmitField('Submit')

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')


class PitchForm(FlaskForm):
  title = StringField('Pitch title')
  category = SelectField("Choose Category",choices=[('Business','Personal Business'),('Product','Product inspirations')])
  pitch = TextAreaField('Your Pitch',validators=[Required()])
  submit = SubmitField('Submit')


class CommentForm(FlaskForm):
  comment = TextAreaField('Your Comment',validators=[Required()])
  submit = SubmitField('Submit') 

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail
from flask_login import LoginManager
from flask_simplemde import SimpleMDE




bootstrap = Bootstrap()
db = SQLAlchemy()
mail = Mail()
photos = UploadSet('photos',IMAGES)
simple = SimpleMDE()



login_manager = LoginManager()
login_manager.session_protection = 'strong' #provides different security levels.
login_manager.login_view = 'auth.login'


def create_app(config_name):

    # inititalizing application
    app = Flask(__name__)

 
    # creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    simple.init_app(app)


    #registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/auth')

    #setting confi

    # configure UploadSet
    configure_uploads(app,photos)
    
    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,error

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from . import main
from flask_login import login_required,current_user
from .. import db,photos
from .forms import  UpdateProfile,PitchForm,CommentForm
from ..models import User,Pitch,Comment



# Views

@main.route('/')
@login_required
def index():

    '''
    View root page function that returns the index page and its data

    '''

    # Getting popular movie

    return render_template('index.html')


@main.route('/pitch')
def pitches():
  pitches = Pitch.query.all()
  Xactly = Pitch.query.filter_by(category='Xactly').all()
  product = Pitch.query.filter_by(category='Product').all()
 

  return render_template('pitch.html',pitches=pitches,Xactly=Xactly,product=product)  



@main.route('/user/<uname>')
@login_required
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user) 
    
@main.route('/user/<uname>/update',methods = ['GET','POST'])
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname = user.username))

    return render_template('profile/update.html',form = form)    



@main.route('/user/<uname>/update/pic',methods = ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname = uname))


@main.route('/pitch/new',methods = ['GET','POST'])
@login_required
def new_pitch():
  form = PitchForm()

  if form.validate_on_submit():
    title=form.title.data
    category = form.category.data
    pitch = form.pitch.data
    # author = current_user
    new_pitch = Pitch(title=title,category=category,pitch=pitch)

    db.session.add(new_pitch)
    db.session.commit()

    return redirect(url_for('main.pitches',id=new_pitch.id))

  return render_template('create_pitch.html',title='Add Your Pitch',pitch_form=form)

@main.route('/comments/<int:id>',methods=['GET','POST'])
def comment_review(id):
  comment = CommentForm()
  pitch=Pitch.query.get(id)

  if comment.validate_on_submit():
    content = comment.comment.data
    
    new_post = Comment(comment=content,title=pitch.id)

    db.session.add(new_post)
    db.session.commit()  
    
  post = 'Post Your Comment'
  user=User.query.get(id)
  comments = Comment.query.filter_by(title=pitch.id).all()  
  if pitch is None:
    abort(404)
  return render_template('comments.html',comment_form=comment,post=post,comments=comments,pitch=pitch,user=user)          

app/templates/base.html
{% extends 'bootstrap/base.html'%}
<!-- Navbar block -->
{% block navbar %}
{% include 'navbar.html' %}

{% endblock %}
{% block pitches%}
{%include 'pitches.html'%}
{%endblock%}


{%block styles %}
  {{super()}}
  <!--Importing the simple mde css and js files  -->
  {{ simplemde.css}}
  {{ simplemde.js }}

{% endblock %}

app/templates/comments.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}


{% block styles %}
  {{super()}}
  <link rel="stylesheet" href="{{url_for('static',filename='css/styles.css')}}">
{% endblock %}

{% block content %}
<style>
  body{
      background: url("{{url_for('static',filename='images/mable.jpg')}}") center/cover no-repeat;
  }
</style>

<div class="container-fluid">
  <div class="row comment-area">
    <div class="col-md-4">
        <div id="post-title">
          <h2>{{post}}</h2>
        </div>
          {{ wtf.quick_form(comment_form) }}  
      </div>
      <div class="col-md-8" id="post-section">
           <!-- {{format_comment|safe}} -->
        {% for post in comments%}
        <div class="jumbotron">
        <div class="card peach-gradient color-block mb-3 mx-auto z-depth-1 post-card">
          <h4 class="card-title">{{pitch.title}}</h4>
          <p class="card-body">" ...{{post.comment}} "</p>
          <p class="card-footer"><b>{{user.username}}</b> ,this your pitch </p>
        </div>  
      </div>
        {% endfor %}
      </div>
  </div>  
</div>

{% endblock %}

app/templates/create_pitch.html
{% extends 'base.html'%}

<div class="row row-cols-1 row-cols-md-3 g-4">
    <div class="col">
      <div class="card h-100">
        <img src="..." class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">Card title</h5>
          <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        </div>
        <div class="card-footer">
          <small class="text-muted">Last updated 3 mins ago</small>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card h-100">
        <img src="..." class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">Card title</h5>
          <p class="card-text">This card has supporting text below as a natural lead-in to additional content.</p>
        </div>
        <div class="card-footer">
          <small class="text-muted">Last updated 3 mins ago</small>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card h-100">
        <img src="..." class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">Card title</h5>
          <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.</p>
        </div>
        <div class="card-footer">
          <small class="text-muted">Last updated 3 mins ago</small>
        </div>
      </div>
    </div>
  </div>


  <!-- ===================create account -->

{% import 'bootstrap/wtf.html' as wtf %}


{% block styles %}
  {{super()}}
  <link rel="stylesheet" href="{{url_for('static',filename='css/styles.css')}}">
{% endblock %}


{% block content %}
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-2"></div>
      <div class="col-md-8">
          <div id="pitch-title">
            <h2>{{title}}</h2>
          </div>              
            {{wtf.quick_form(pitch_form)}}
      </div>
    </div >
</div>
{%endblock%}      

app/templates/fourOwfour.html
{% extends 'base.html'%}

<!-- {% block content %} -->

    <h1 class="text-center">WHOOOPS! we can't find that page</h1>

<!-- {% endblock %} -->

app/templates/index.html
{%extends 'base.html'%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/bootstrap.min.css')}}"/>
    <!-- <link rel="stylesheet" href="{{url_for('static',filename='styles.css')}}"/> -->
    {% endblock %}
    {% block scripts%}
    {{ super() }}
    <script src="{{url_for('static',filename='js/bootstrap.min.js')}}"></script>
    <script src="{{url_for('static',filename='js/script.js')}}"></script>
    {% endblock %}

        
</head>
<body>
    {%block content%}
  <style>
      body{
          background: url("{{url_for('static',filename='images/wallpaper-photos-31.jpg')}}") center/cover no-repeat;
      }
  </style>
   
    <div class="container">
        <h2 class="text-light text-center">Welcome to Pitch website, designed by Joe Gakumo</h2>
        <h3 class="text-center text-light">Great Sales Pitch Examples</h3>
        <div class="">     
            <div class="row">
                <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
                    <div class="card text-white bg-primary mb-3" style="max-width: 18rem;">
                        <div class="card-header"><h1>Xactly</h1></div>
                        <div class="card-body">
                            <h5 class="card-title">Xactly pitch</h5>
                            <p class="card-text">The Xactly pitch focuses on the problem their customer has — an important part of a successful pitch. I discussed the "me monster" above, and you should be wary of it when creating a pitch. Xactly does this well. The trick is to address your customer's problems and concerns and highlight how your product or service solves these problems. In the case of Xactly, it's about getting people off cumbersome legacy systems and Excel spreadsheets.</p>
                            <a href="{{ url_for('main.new_pitch') }}" ><button class="btn bg-light">Create and Comment</button></a>
                             <br>
                            <!-- <button id="like"  style="font-size: 1.3rem; background: none; color: rgb(105, 194, 17); padding: 0 1rem; border: none;">0</button>
                            <button id="dislike" onclick="downvote()" style="font-size: 1.3rem; background: none; color: rgb(105, 194, 17); padding: 0 1rem; border: none;">0</button> -->
                               
                           <i class="bi bi-hand-thumbs-up-fill ml-5"onclick="upvote()" id="like" style="font-size: 2rem; color: rgb(173, 31, 31);margin-left: 2rem;">0</i>
                          <i class="bi bi-hand-thumbs-down-fill bi-danger"onclick="downvote()"  id="dislike" style="font-size: 2rem;color: black;">0</i>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
                    <div class="card text-white bg-secondary mb-3" style="max-width: 18rem;">
                        <div class="card-header"><h1>Vidyard</h1></div>
                        <div class="card-body">
                            <h5 class="card-title">Vidyard pitch</h5>
                            <p class="card-text">Vidyard is the key to making remote selling easy. From prospecting to proposals, record and send videos that add a personal touch at all stages of the sales cycle. Email isn’t dead, but it sure is boring. With Vidyard, you can record and send videos in just a few clicks – perfect for busy sales reps trying to break into inboxes or marketers trying to make a splash."</p>
                            <a href="{{ url_for('main.new_pitch') }}" ><button class="btn bg-light">Create and Comment</button></a>
                             <br>
                             <i class="bi bi-hand-thumbs-up-fill ml-5"onclick="upvote1()" id="like1" style="font-size: 2rem; color: rgb(173, 31, 31);margin-left: 2rem;">0</i>
                             <i class="bi bi-hand-thumbs-down-fill bi-danger"onclick="downvote1()"  id="dislike1" style="font-size: 2rem;color: black;">0</i>
                        </div>
                    </div>
                </div>
                <div class=" col-lg-3 col-md-4 col-sm-6 col-xs-12">
                    <div class="card text-white bg-success mb-3" style="max-width: 18rem;">
                        <div class="card-header"><h1>Thrivent Financial</h1></div>
                        <div class="card-body">
                            <h5 class="card-title">Thrivent Financial pitch</h5>
                            <p class="card-text">Thrivent Financial is another financial firm that focuses on the buyer in its pitch. Like in the previous pitch, it emphasizes helping prospects do what they most want to do after managing their finances. By implementing a similar strategy, you can craft your pitch so that prospects understand what they can achieve if they do business with you.</p>
                            <a href="{{ url_for('main.new_pitch') }}" ><button class="btn bg-light">Create and Comment</button></a>
                             <br>
                             <i class="bi bi-hand-thumbs-up-fill ml-5"onclick="thumbs()" id="likes2" style="font-size: 2rem; color: rgb(173, 31, 31);margin-left: 2rem;">0</i>
                             <i class="bi bi-hand-thumbs-down-fill bi-danger" onclick="mythumb()"  id="down" style="font-size: 2rem;color: black;">0</i>
                        
                            </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
                    <div class="card text-white bg-danger mb-3" style="max-width: 18rem;">
                        <div class="card-header"><h1>Edward Jones</h1></div>
                        <div class="card-body">
                            <h5 class="card-title">Edward Jones pitch</h5>
                            <p class="card-text">Edward Jones, a financial advising firm, creates a personal, resonant pitch by focusing entirely on the prospect or buyer. You rarely hear about them in this pitch, which is another great model to follow when creating your own pitch. While this is geared toward consumers rather than another business, it’s a great example of how you can write a pitch that resonates with your prospects while offering plenty of information about what you do.</p>
                            <a href="{{ url_for('main.new_pitch') }}" ><button class="btn bg-light">Create and Comment</button></a>
                             <br>
                             <i class="bi bi-hand-thumbs-up-fill ml-5"onclick="upvote3()" id="like3" style="font-size: 2rem; color: rgb(173, 31, 31);margin-left: 2rem;">0</i>
                             <i class="bi bi-hand-thumbs-down-fill bi-danger"onclick="downvote3()"  id="dislike3" style="font-size: 2rem;color: black;">0</i>
                        </div>
                    </div>
                </div>
            </div>    
        </div>
        <div class="">     
            <div class="row">
                <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
                    <div class="card text-white bg-warning mb-3" style="max-width: 18rem;">
                        <div class="card-header"><h1>Van Jones</h1></div>
                        <div class="card-body">
                            <h5 class="card-title">Primary card title</h5>
                            <p class="card-text">In this pitch to businesses and organizations looking for a speaker, Van Jones emphasizes his expertise — then highlights the fact that his reach will apply to everyone who listens to him. In a similar way, you can use the authoritativeness of your business to stand out, then turn around and address any concerns an organization might have about doing business with you. Here, Van Jones subtly addresses the current political climate by emphasizing that his speeches will resonate with anyone regardless of their background.</p>
                            <a href="{{ url_for('main.new_pitch') }}" ><button class="btn bg-light">Create and Comment</button></a>
                             <br>
                             <i class="bi bi-hand-thumbs-up-fill ml-5"onclick="upvote4()" id="like4" style="font-size: 2rem; color: rgb(173, 31, 31);margin-left: 2rem;">0</i>
                             <i class="bi bi-hand-thumbs-down-fill bi-danger"onclick="downvote4()"  id="dislike4" style="font-size: 2rem;color: black;">0</i>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
                    <div class="card text-white bg-info mb-3" style="max-width: 18rem;">
                        <div class="card-header"><h1>G2Crowd</h1></div>
                        <div class="card-body">
                            <h5 class="card-title">Secondary card title</h5>
                            <p class="card-text">This is an interesting way to build your pitch: Make a note of what really annoys your customer and pitch how your service can resolve this grievance. It's another way of reframing the customer's needs, and it works because it's a powerful way to describe the situation.

                                When they discuss how you're being told by analysts what to do, or people who haven't used a product, they highlight a clear disconnect in the market between what you need and what you get. The company allows verified users of products to write reviews and becomes an essential resource for their users.</p>
                            <a href="{{ url_for('main.new_pitch') }}" ><button class="btn bg-light">Create and Comment</button></a>
                             <br>
                             <i class="bi bi-hand-thumbs-up-fill ml-5"onclick="upvote5()" id="like5" style="font-size: 2rem; color: rgb(173, 31, 31);margin-left: 2rem;">0</i>
                             <i class="bi bi-hand-thumbs-down-fill bi-danger"onclick="downvote5()"  id="dislike5" style="font-size: 2rem;color: black;">0</i>
                        </div>
                    </div>
                </div>
                <div class=" col-lg-3 col-md-4 col-sm-6 col-xs-12">
                    <div class="card text-dark bg-light mb-3" style="max-width: 18rem;">
                        <div class="card-header"><h1>Gap Inc</h1></div>
                        <div class="card-body">
                            <h5 class="card-title">Success card title</h5>
                            <p class="card-text">"Gap Inc. is a leading global retailer with a collection of brands including Old Navy, Gap, Banana Republic, and Athleta. We're committed to serving the needs of our customers while delivering long-term value to our shareholders.”Gap is better known as a clothing brand, but the company behind it, Gap Inc, is a publicly traded firm with multiple successful brands under its belt. In its pitch to its potential investors, Gap Inc emphasizes its dominant position in the marketplace while ensuring that the company will be a secure long-term</p>
                            <a href="{{ url_for('main.new_pitch') }}" ><button class="btn bg-light">Create and Comment</button></a>
                             <br>
                             <i class="bi bi-hand-thumbs-up-fill ml-5"onclick="upvote6()" id="like6" style="font-size: 2rem; color: rgb(173, 31, 31);margin-left: 2rem;">0</i>
                             <i class="bi bi-hand-thumbs-down-fill bi-danger"onclick="downvote6()"  id="dislike6" style="font-size: 2rem;color: black;">0</i>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
                    <div class="card text-white bg-success mb-3" style="max-width: 18rem;">
                        <div class="card-header"><h1>Merck</h1></div>
                        <div class="card-body">
                            <h5 class="card-title">Danger card title</h5>
                            <p class="card-text">'For 130 years, Merck (known as MSD outside of the U.S. and Canada) has been inventing for life, bringing forward medicines and vaccines for many of the world’s most challenging diseases in pursuit of our mission to save and improve lives.”

                                If you were a hospital or pharmacy considering using Merck’s solutions, you’d be convinced by this pitch. Why?
                                
                                Merck knows that values and strong scientific foundations drive business decisions in the healthcare industry. They capitalize on that by emphasizing their long history and tying their work into their mission. In that way, it sends a message that resonates with its target audience.</p>
                            <a href="{{ url_for('main.new_pitch') }}" ><button class="btn bg-light">Create and Comment</button></a>
                             <br>
                             <i class="bi bi-hand-thumbs-up-fill ml-5"onclick="upvote7()" id="like7" style="font-size: 2rem; color: rgb(173, 31, 31);margin-left: 2rem;">0</i>
                             <i class="bi bi-hand-thumbs-down-fill bi-danger"onclick="downvote7()"  id="dislike7" style="font-size: 2rem;color: black;">0</i>
                        </div>
                    </div>
                </div>
            </div>
        </div>   
    </div>
    {%endblock%}
</body>
  
</html>

app/templates/navbar.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    
    <link rel="stylesheet" href="{{url_for('static',filename='navbar.css')}}"/>
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}"/>
   
  </head>
  <body>
    <div class="container">
    <div class="navbar navbar-inverse" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="/" style="color: black;font-style: italic;font-size: 3rem;text-decoration: none;">Pitches</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right d-inline" style="font-size: 2.5rem;">
                 
                  {% if current_user.is_authenticated %}
                  <li><a href="#"  style="color: green;font-style: italic;text-decoration: none;"><span style="color: black;">signed as: </span>{{current_user.username}}</a></li>
                  <li><a href="{{ url_for('main.new_pitch') }}" style="color: black;font-style: italic;text-decoration: none;">New pitch</a></li>
                 
                  <li><a href="{{url_for('main.profile',uname = current_user.username)}}"  style="color: black;font-style: italic;text-decoration: none;">Profile</a></li>
                  <li><a href="{{url_for('auth.logout')}}"  style="color: black;font-style: italic;text-decoration: none;">SignOut</i></a></li>
                  {% else %}
                  <li><a href="#" style="color: black;font-style: italic;text-decoration: none;">User</a></li>
                  <li><a href="{{url_for('auth.login')}}"  style="color: black;font-style: italic;text-decoration: none;">Sign in</a></li>
                  {%endif%}
                </ul>
            </div>
        </div>
        </div>
    </div>
  </body>
</html>

app/templates/pitch.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block styles %}
  {{super()}}
  <link rel="stylesheet" href="{{url_for('static',filename='css/styles.css')}}">
{% endblock %}
{% block content %}
  <div class="container-fluid user-pitches">
    <div class="jumbotron">
        <div class="row">
            <h2 id="p-cat" style="text-align: center"> PITCH CATEGORIES </h2>
        </div>
        <div class="row main">
        <div class="col-md-2"></div>
          <div class="col-md-8">
            <div class="row pitch-section">
              <h3 class="cats">Motivation Pitch</h3>
              {% for pitch in Xactly %}
              <div class="card peach-gradient color-block mb-3 mx-auto z-depth-1">
                <h4 class="card-title">{{pitch.title}}</h4>
                <p class="card-body">" {{pitch.pitch}}</p>
                <p class="card-footer"><a href="/comments/{{pitch.id}}"><button class="btn btn-light">Comment</button></a></p>
              </div>
              {% endfor %}
            </div>
            <div class="row">
              <h3 class="cats">Inspiration</h3>
              {% for pitch in product %}
              <div class="card peach-gradient color-block mb-3 mx-auto z-depth-1">
                <h4 class="card-title">{{pitch.title}}</h4>
                <p class="card-body">" {{pitch.pitch}}</p>
                <p class="card-footer"><a href="/comments/{{pitch.id}}"><button class="btn btn-light">Comment</button></a></p>
              </div>
              {% endfor %}
            </div> 
          </div>
          <div class="col-md-2"></div>
        </div>
      
  </div>
{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}

{% block content %}
<style>
  body{
      background: url("{{url_for('static',filename='images/mable.jpg')}}") center/cover no-repeat;
  }
</style>


<div class="container jumbotron">

<div class="row">


  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    {% if user.bio %}
      <p> {{user.bio}}</p>

    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}

    {% if user == current_user %}
      <a href="{{url_for('main.update_profile',uname = user.username)}}">Edit profile</a>
    {% endif %}

  </div>
  <div class="col-md-4">
    {% if user.profile_pic_path %}

    <img src="{{url_for('static',filename = user.profile_pic_path)}}" alt="" class="img-thumbnail">

    {%else%}

    <p>No profile picture</p>

    {% endif %}

    {% if user == current_user %}
    <form  action="{{url_for('main.update_pic',uname = user.username)}}" method="post" enctype = "multipart/form-data">

      <input type="file"  name="photo" class="form-control" required>
      <input class="btn btn-success btn-sm" type="submit">
    </form>
      {% endif %}
  </div>


</div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}